version: '3.5'
services:
  node-api:
    container_name: sp-smaugbudget-app
    restart: always
    ports:
      - "8080:8080"
    image: sp-smaugbudget-node-js
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - /node_modules
    command: "npm start"
    networks:
      - sp-network
    environment:
      - NODE_ENV=docker
    depends_on: 
      - mongo-db

  mongo-db:
    image: mongo:4.2
    container_name: sp-smaugbudget-mongodb
    ports:
      - "27017-27019:27017-27019"
    networks:
      - sp-network

networks:
  sp-network:
    name: sp-network
